uzbek_mapping={
    "My Love in Franks": "Franksdagi Sevgilim",
    "Your Lie in April": "Aprel yolg'oni",
    "Naruto Season 1": "Naruto 1 - fasl",
    "Naruto Season 2": "Naruto 2-fasl",
    "The Rising of the Shield Hero": "Davolovchi qahramon",
    "One Piece": "ONE PIECE",
    "Naruto Movies": "NARUTO BARCHA FILMLAR",
    "Mortal Kombat": "Mortal Kombat",
    "The Promised Neverland": "Va'da qilingan Neverland",
    "I've Been Killing Slimes for 300 Years": "300 yil shiliqlarni o'ldirib, eng yuqori darajaga yetganimi bilmi qoldim",
    "The Promised Neverland Season 2": "Vada qilingan Neverland 2-fasl",
    "The Rising of the Shield Hero Season 1": "QALQON QAHRAMONI 1-FASL",
    "Mashle: Magic and Muscles": "SEHR VA MUSHAKLAR",
    "Final Call": "OXIRGI CHAQIRUVCHI",
    "Farming Life in Another World": "O'ZGA DUNYODA FERMERLIK HAYOTIM",
    "The City I Lost When I Disappeared": "Men yo'q bo'lgan yagona yo'qolgan shahar",
    "In Another World": "O'ZGA DUNYODA",
    "In Another World With My Smartphone Season 1": "SMARTFONIM BILAN 1-FASL",
    "Leveling Up in Another World": "O'zga dunyoda darajamni ko'tarib, bu dunyoda ham tengsiz bo'ldim: Hayotim qanday o'zgargani haqida",
    "Arifureta: From Commonplace to World's Strongest Season 1": "ARIFURETTA ENG KUCHLI HUNARMAND 1-FASL",
    "Charlotte": "Sharlotta",
    "Black Summoner": "QORA CHAQIRUVCHI",
    "Moon Trip": "OY SAYOHATI",
    "Moon Trip Season 2": "OY SAYOHATI 2-fasl",
    "Ao Ashi": "Ao ashi",
    "NieR:Automata": "NIER AVTOMATLAR",
    "Deca-Dence": "Deka-dens",
    "Solo Leveling": "SOLO LEVELING",
    "Mashle: Magic and Muscles Season 2": "Sehr va Mushaklar 2-fasl",
    "Attack on Titan Season 1": "TITANLAR HUJUMI 1-FASL",
    "Attack on Titan Season 2": "TITANLAR HUJUMI 2-FASL",
    "Attack on Titan Season 3": "TITANLAR HUJUMI 3-FASL",
    "Attack on Titan Season 4": "TITANLAR HUJUMI 4-FASL",
    "The Quintessential Quintuplets Season 1": "BESH KELIN 1-FASL",
    "The Quintessential Quintuplets Season 2": "BESH KELIN 2-FASL",
    "The Quintessential Quintuplets Movie": "BESH KELIN SO'NGI FILM",
    "Konosuba Season 1": "BU AJOYIB DUNYO 1-FASL",
    "Konosuba Season 2": "BU AJOYIB DUNYO 2-FASL",
    "Isekai Chef Hero": "BOSHQA DUNYODAN KELGAN OSHPAZ QAHRAMON",
    "Fatmasoft Monologue Season 1": "FATMASEFT MANALOGI 1-FASL",
    "Berserk 1997": "BERSERK 1997",
    "Berserk 2022": "BERSERK 2022",
    "Your Name": "SENING ISMING",
    "A Silent Voice": "OVOZ SHAKLI",
    "Patema Inverted": "TESKARI PATEMA",
    "The Tiger and the Fish": "YO'LBARS VA BALIQ",
    "My Uncle's Reincarnation": "TOG'AMNING QAYTA TUG'ULISHI",
    "Heavenly Delusion": "JANNAT SAROBI",
    "The Misfit of Demon King Academy": "IBLISLAR HUKMDORI ANOS",
    "The Misfit of Demon King Academy Season 2": "IBLISLAR HUKMDORI ANOS 2-FASL",
    "Bo’ta nima qvosz ustoz": "BO'TA NIMA QVOSZ USTOZ",
    "Say I Love You": "SENI SEVAMAN DEB AYT",
    "The Tunnel to Summer, the Exit of Goodbyes": "YOZGI TUNEL HAYRLASHUVI",
    "Greedy Berserk": "OCHKO'Z BERSERK",  # Bu taxminiy
    "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You Season 1": "Seni juda juda juda sevadigan 100-ta qiz 1-fasl",
    "Demon Slayer Season 1": "IBLISLAR QOTILI 1-FASL",
    "Demon Slayer: Mugen Train": "IBLISLAR QOTILI CHEKSIZ POYEZD",
    "Demon Slayer Season 2": "IBLISLAR QOTILI 2-FASL",
    "Demon Slayer Season 3": "IBLISLAR QOTILI 3-FASL",
    "Demon Slayer Season 4": "IBLISLAR QOTILI 4-FASL",
    "One Punch Man": "BIR ZARBLI ODAM",
    "One Punch Man Season 2": "BIR ZARBLI ODAM 2-FASL",
    "Noragami Season 1": "UYSIZ MABUD 1-FASL",
    "Komi Can't Communicate Season 1": "KOMI SAN MULOQOT QILA OLMAYDI 1-FASL",
    "Hyouka": "HYOUKA",
    "The Boy, the Mole, the Fox and the Horse": "Bolakay, Ko'rsichqon,Tulki va Ot",
    "My Love Story with Yamada at Lv999": "Yamada-kunga boʻlgan sevgim darajasi 999",
    "Godzilla: Singular Point": "Godzilla: Singulyar nuqta",
    "Suzume": "Suzume: Eshiklarni Qulflovchi Kalit",
    "Reincarnated as a Sword": "Meni qilich bo'lib qayta tug'ilganim haqida",
    "91 Days": "91 kun",
    "My Happy Marriage": "Mening baxtli turmushim",
    "Kino's Journey: The Beautiful World": "Kino sarguzashtlari: Ajoyib dunyo",
    "Baki Season 1": "JANGCHI BAKI 1-FASL",
    "Baki Season 2": "JANGCHI BAKI 2-FASL",
    "The King's Avatar": "Qirolning avatari",
    "Domestic Girlfriend": "DOMEKANO",
    "Shangri-La Frontier": "SHANGRILA CHEGARASI",
    "Re:Zero − Starting Life in Another World Season 1": "Re:Zero Hayotni noldan boshlash 1-fasl",
    "Re:Zero − Starting Life in Another World Season 2": "Re:Zero Hayotni noldan boshlash 2-fasl",
    "Kaguya-sama: Love is War Season 1": "Kaguya xonim: sevgi bu jang 1-fasl",
    "Kaguya-sama: Love is War Season 2": "Kaguya xonim: sevgi bu jang 2-fasl",
    "Boruto": "BORUTO",
    "Tonari no Seki-kun: The Master of Killing Time": "Vaqt o'ldirish ustasi Seki-kun",
    "Avatar: The Last Airbender": "Avatar: Aang afsonasi",
    "Fullmetal Alchemist": "Po'lat Alkimyogar",
    "Spy x Family": "Josus X Oilasi",
    "Haikyuu!!": "Voleybol (haikyuu)",
    "In Another World With My Smartphone Season 2": "O'zga dunyoda smartfonim bilan 2-fasl",
    "Tokyo Revengers Season 1": "Tokyo qasoskorlari 1-fasl",
    "Tokyo Revengers Season 2": "Tokyo qasoskorlari 2-fasl",
    "Tokyo Revengers Season 3": "Tokyo qasoskorlari 3-fasl",
    "Lycoris Recoil": "Likoris Rekoil",
    "The Eminence in Shadow Season 1": "Soyada ko'tarilish 1-fasl",
    "Zom 100: Bucket List of the Dead": "Omadsiz tirik murda",
    "Wise Man's Grandchild": "Past belgili qudratli donishmand",
    "Love Me Seriously": "Meni jiddiy sev",
    "Kung Fu Panda 4": "KUNFU PANDA 4",
    "Parallel World Pharmacy": "Parallel dunyodagi farmaseft",
    "Parasyte: The Maxim": "Parazit: Hayot saboqlari",
    "Tomodachi Game": "Tomodachi o'yini",
    "Record of Ragnarok": "Ragnarok Yilnomasi",
    "Frieren: Beyond Journey's End": "Friren: so'nggi manzilga kuzatuvchi",
    "The Millionaire Detective – Balance: UNLIMITED": "Millioner Detektiv",
    "I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too": "O'zga dunyoda oilali bo'ldim",  # bu taxminiy, tekshirsa yaxshi bo'lardi
    "The Witch and the Beast": "Jodugar va maxluq",
    "The War of Witches Season 1": "Jodugarlar jangi 1-fasl",  # taxminiy
    "Mob Psycho 100 Season 1": "MOB PSIXO 100 1-FASL",
    "The War of Witches Season 2": "Jodugarlar jangi 2-fasl",
    "Mob Psycho 100 Season 2": "MOB PSIXO 100 2-FASL",
    "The War of Witches: Zero (Movie)": "Jodugarlar jangi 0 film",
    "Mob Psycho 100 Season 3": "Mob psixo 100 3-fasl",
    "Clockwork Planet": "BIR SOATLI QIZCHA",
    "Clockwork Planet Season 2": "BIR SOATLI QIZCHA 2-FASL",
    "Clockwork Planet Season 3": "BIR SOATLI QIZCHA 3-FASL",
    "Classroom of the Elite": "Elita sinfi",
    "Classroom of the Elite Season 2": "Elita sinfi 2-fasl",
    "Tokyo Ghoul Season 1": "TOKYO GUL 1-FASL",
    "Tokyo Ghoul Season 2": "TOKYO GUL 2-FASL",
    "Akudama Drive": "Akudama drive",
    "Takt Op. Destiny": "Takt Opus Qismati",
    "Tokyo Ghoul:re Season 1": "TOKYO GUL 3-FASL",
    "Tokyo Ghoul:re Season 2": "TOKYO GUL 4-FASL",
    "Chainsaw Man": "Arra odam",
    "Burning Kabaddi": "OLOVLI KABADI",
    "Classroom of the Elite Season 3": "Elita sinfi 3-fasl",
    "Tekken: Bloodline": "TEKKEN",
    "Arcane Season 1": "Arkeyn: Afsonalar ligasi 1-fasl",
    "The Eminence in Shadow Season 2": "Soyada ko'tarilish 2-fasl",
    "Blue Lock Season 1": "KO'K ZINDON 1-FASL",
    "Love at the Fingertips": "Barmoqlar uchidagi sevgi",
    "Akkun to Kanojo": "Akkun va uning qizi",
    "Monster": "MONSTER",
    "Arifureta Season 2": "ARIFURETTA ENG KUCHLI HUNARMAND 2-FASL",
    "How Not to Use Healing Magic": "Davolash sehridan foydalanishni noto'g'ri usuli",
    "The 8th Son? Are You Kidding Me?": "Sakkizinchi o'gil hazillashyapsilarmi",
    "Ninja Kamui": "Ninja kamui",
    "The Seven Deadly Sins": "Yetti o'lim gunohi",
    "Summertime Render": "Yoz vaqti",
    "Dragon Ball": "DRAGON BALL",
    "Rokka: Braves of the Six Flowers": "Olti gul qahramonlari",
    "Kingdom of Ruin": "Harobalar qirolligi",
    "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway": "Soqolimni olib, yuqori maktab qizini uyimga olib keldim",
    "Tales of Wedding Rings": "Nikoh uzuklari haqida afsona",
    "My Hero Academia Season 1": "Mening qahramonlik akademiyam 1-fasl",
    "My Hero Academia Season 2": "Mening qahramonlik akademiyam 2-fasl",
    "My Hero Academia Season 3": "Mening qahramonlik akademiyam 3-fasl",
    "My Hero Academia Season 4": "Mening qahramonlik akademiyam 4-fasl",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? Season 1": "Zindonda Qizlar bilan uchrashish yomonmi ? 1-fasl",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? Season 2": "Zindonda Qizlar bilan uchrashish yomonmi ? 2-fasl",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? Season 3": "Zindonda Qizlar bilan uchrashish yomonmi ? 3-fasl",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? Season 4": "Zindonda Qizlar bilan uchrashish yomonmi ? 4-fasl",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? Movie": "Zindonda Qizlar bilan uchrashish yomonmi ? Film",
    "Orient": "Orient",
    "Hell's Paradise": "Jahannam jannati",
    "Child of Kamiari Month": "Tabiat farzandi",
    "My Stepmom’s Daughter Is My Ex": "O'gay onamning qizi mening sobiq sevgilim",
    "Dororo": "Dororo",
    "My Hero Academia Season 5": "Mening qahramonlik akademiyam 5-fasl",
    "My Hero Academia Season 6": "Mening qahramonlik akademiyam 6-fasl",
    "My Hero Academia: The Movie": "Mening qahramonlik akademiyam FILM",
    "The Dangers in My Heart": "Yoshlik ifori",  # ehtimoliy moslik
    "Seven Lives": "Yetti hayot tsikli",
    "Call of the Night": "Bo'sani jalb etib",  # taxminiy
    "Japan Sinks: 2020": "Yaponiya falokati 2020",
    "Gangsta.": "Gangsta",
    "The Great Cleric": "Ofis hodimi buyuk avliyo sifatida qayta tug'ilishi",
    "Tokyo Revengers: Tenjiku Arc": "To'qqizinchi to'da",  # taxminiy
    "Sword Art Online Season 1": "Qilich san’ati online 1-fasl",
    "Sword Art Online Season 2": "Qilich san’ati online 2- fasl",
    "Beyond the Boundary": "Chegara ortida",
    "Beyond the Boundary: I'll Be Here – Future": "Chegara ortida ( FILM )",
    "Sword Art Online Season 3": "Qilich san’ati online 3-fasl",
    "I'm Standing on a Million Lives": "Menda Million Hayot Bor",
    "World of Leadale": "Lideyl dunyosi",
    "Death Note": "O'lim kundaligi",
    "My Dress-Up Darling": "Bu chinni qiz sevib qoldi",
    "The Garden of Words": "Nafis so'zlar bog'i",
    "KonoSuba: An Explosion on This Wonderful World!": "Bu ajoyib Dunyoni Portlashlar bilan Yoritib",
    "The Tunnel to Summer, the Exit of Goodbyes": "O'rmonda Tilla Qo'ng'izlar Yaltiraydi",  # taxminiy
    "Gleipnir": "Gleipnir",
    "Darwin's Game": "Darvin o'yini",
    "Godzilla x Kong: The New Empire": "Godzila va Kong: Yangi imperiya",
    "No Game No Life": "O'yinsiz hayot yo'q",
    "No Game No Life: Zero": "Oʻyinsiz Hayot Yoʻq:ZERO film",
    "Summoned to Another World for a Second Time": "Oʻzga dunyoga ikkinchi marta chaqirilganim haqida",
    "Fuuto PI": "Futo detektivlari",
    "Edens Zero": "Edens zero",
    "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat": "Dunyodagi eng zo'r qotil",
    "Housing Complex C": "Turar-joy majmuasi",
    "The Legendary Hero is Dead!": "Abadiy qudrat",  # taxminiy
    "Death Parade": "O'lim sahnasi",
    "The Tale of the Outcasts": "Halqa yilnomalari",  # taxminiy
    "Between Two Fires": "Ikki o't orasida",  # taxminiy yoki original asar bo'lishi mumkin
    "Overlord Season 1": "Hukumdor 1-fasl",
    "Overlord Season 2": "Hukmdor 2-fasl",
    "Overlord Season 3": "Hukmdor 3-fasl",
    "Overlord Season 4": "Hukmdor 4-fasl",
    "Night Owl Song": "Tungi boyqushlar kuyi",  # taxminiy
    "5 Centimeters per Second": "Soniyasiga 5 Santimetr",
    "Akudama Drive": "Qotil seven",  # taxminiy, agar boshqa bo‘lsa aniqlashtiramiz
    "Firefighter Daigo: Rescuer in Orange": "Daygo: O't ochiruvchi",
    "Lost Fairies": "Yo'qolgan parilar",  # taxminiy
    "Akudama Drive Season 2": "Qotil seven 2-fasl",  # taxminiy
    "Goblin Slayer": "Goblinlar qotili",
    "Goblin Slayer Season 2": "Goblinlar qotili 2-fasl",
    "KonoSuba: God's Blessing on This Wonderful World!": "KONOSUBA - God's Blessing on This Wonderful World!",
    "Horimiya": "Horimiya",
    "Horimiya: The Missing Pieces": "Horimiya 2-fasl",
    "The World's Best Assassin Gets Reincarnated in Another World as a Liar Mage": "Boshqa dunyodan kelgan Yolg‘onchi Sehrgar",  # taxminiy
    "To Your Eternity": "Sen uchun o'lmas",
    "To Your Eternity Season 2": "Sen uchun o'lmas 2-fasl",
    "Kiki’s Delivery Service": "Kiki eltuv hizmati",
    "The Duke of Death and His Maid": "Bosning qizi va uning enagasi",
    "Take Me to the Moon": "Meni oyga olib ket",
    "Take Me to the Moon Season 2": "Meni oyga olib ket 2-fasl",
    "My Happy Marriage": "Ziyofatchi kunim",  # taxminiy
    "Yesterday wo Utatte": "Kechagi kunni o'ylab",
    "Silver Guardian": "Kumush qo'riqchi",
    "Skeleton Knight in Another World": "Skilet ritsar o'zga dunyoda",
    "More Real Than Real": "Real dunyodan haqiqiyroq o'yin",  # taxminiy
    "Haikyuu!! Season 2": "Voleybol 2-fasl",
    "Haikyuu!! Season 3": "Voleybol 3-fasl",
    "Haikyuu!! OVAs": "Voleybol (ova)",
    "Haikyuu!! Season 4": "Voleybol 4-fasl",
    "Platinum End": "Platina yakun",
    "High Card": "Yuqori karta",
    "The Tale of the Forgotten Beasts": "Afsonada unutilgan maxluqlar",  # taxminiy
    "Kuroko's Basketball": "Basketbol kuroko",
    "Oshi no Ko": "Idol farzandlari",
    "The Legendary Hero is Dead!": "Afsonaviy Iloh: Yilnomasi",
    "My Brother Annoys Me": "Akam asabimga tegyapti",  # taxminiy
    "Another": "Another",
    "To Your Eternity": "Abadiylik qo'riqchisi",
    "Am I Actually the Strongest?": "Aslida men eng kuchlisimanmi?",
    "Reincarnated as a Slime": "Maxluq bo'lib qayta tug'ulishim",
    "My Daughter is Beautiful and More": "Meni qizcham nafaqat gozal",  # taxminiy
    "I Love My Big Brother": "Akamni sevaman",  # taxminiy
    "Ayakashi Triangle": "Ayakashi uchburchagi",
    "Cyberpunk: Edgerunners": "KyberPunk: Kiber Qochqin",
    "Arknights": "Arknayt",
    "Would You Fall for a Pervert if She's Cute?": "Agar buzuq odam yoqimli bo'lsa uni yoqtraszmi ?",
    "Crazy for Passion": "Aqildan Ozgan Ehtiros",  # taxminiy
    "I Was Reincarnated as the 7th Prince": "Yettinchi shahzoda sifatida qayta tugʻildim va endi sehrimni istaganimcha kuchaytiraman",
    "Vermeil in Gold": "Oltin rangli Vermeyel",
    "What If...?": "Agarda...",
    "What If...? Season 2": "Agarda... 2-fasl",
    "Zom 100: Bucket List of the Dead": "Zombie 100 : O'lim oldi rejalar",
    "Zom 100: Bucket List of the Dead (Movie)": "Zombie 100 : kino",
    "Tower of God": "Mabud minorasi",
    "Metallic Rouge": "Metall ruj",
    "Ayaka: A Story of Bonds and Wounds": "Ayaka",
    "The Foolish Rabbit Girl's Dreams Are Misunderstood": "Bu ahmoq, quyon qizning orzularini tushunmaydi",  # taxminiy
    "Akame ga Kill!": "Qotil Akame",
    "Dr. Stone": "Doktor stoun",
    "Wind Breaker": "Shamol sindruvchi",
    "Harem in the Labyrinth of Another World": "Boshqa dunyodagi Garem labirinti",
    "Restaurant to Another World": "Boshqa dunyodagi restoran",
    "A Couple of Cuckoos": "Bir juft kakkular",
    "We Were There": "Bizdan bir kun oldin",
    "We Were There Season 2": "Bizdan bir kun oldin 2-fasl",
    "Yuan Long": "Boshqa dunyodan Yuan Long",
    "Battle Game in 5 Seconds": "Besh soniyadan keyin",
    "The World God Only Knows": "Bezori qirolicha: Yigitlarni uruvchi qiz",  # taxminiy
    "My Love Story with Yamada at Lv999": "Oʻrta maktabdagi sevgim kutilganidek ish bermadi",  # bu boshqachamikin?
    "Hokkaido Gals Are Super Adorable!": "Hokkaido qizlari super yoqimtoy",
    "Eromanga Sensei": "Eromanga Sensei",
    "Eromanga Sensei OVA": "Eromanga Sensei OVA",
    "Dr. Stone Season 2": "Doktor stoun 2-fasl",
    "I Don’t Understand What My Husband is Saying": "Erimni tushunmayapman",
    "The Fruit of Evolution": "Evolutsiya Mevasi",
    "Dr. Stone Season 3": "Doktor stoun 3-fasl",
    "Dr. Stone Season 3 Part 2": "Doktor stoun 3-fasl (2-bo'lim)",
    "Dr. Stone: Ryusui": "Doktor stoun (film)",
    "Rainbow": "Kamalak",
    "Reach You": "Senga intilib",  # aslida "Kimi ni Todoke"
    "The Exorcist Reincarnated in Another World": "Egzartist boshqa dunyoda qayta tug'ilib eng kuchli bo'lishga intiladi",  # taxminiy
    "Reach You Season 2": "Senga intilib 2-fasl",
    "Noragami Season 2": "Uysiz ma'bud 2-fasl",
    "Go, President!": "Olg'a prezident",  # taxminiy
    "Karakuri Circus": "Qo'g'irchoqlar sirki",
    "Cautious Hero: The Hero is Overpowered but Overly Cautious": "O'ta ehtiyotkor o'lmas qahramon",
    "The Fruit of Grisaia": "Grisaia mevasi",
    "Yamada and the Seven Witches": "Yamada va yetti jodugar qiz",
    "No Matter How Genius I Am, I Still Struggle in Another World": "Daholar uchun oʻzga dunyoda yashash ham muammo emas",  # taxminiy
    "The Rising of the Shield Hero Season 2": "Qalqon qahramoni 2-fasl",
    "The Rising of the Shield Hero Season 3": "Qalqon qahramoni 3-fasl",
    "Masamune-kun's Revenge": "Masamune qasosi",
    "Masamune-kun's Revenge R": "Masamune qasosi 2-fasl",
    "Seraph of the End": "So'ngi serafim",
    "Seraph of the End Season 2": "So'ngi serafim 2-fasl",
    "The Dangers in My Heart": "Yuragimdagi xavflar",
    "The Dangers in My Heart Season 2": "Yuragimdagi xavflar 2-fasl",
    "Magi: The Labyrinth of Magic": "Magi:Sexrli labirint",
    "Fate/Stay Night": "Taqdir:Jang kechasi",
    "My Unique Skill Makes Me OP Even at Level 1": "Mening noyob mahoratim",
    "The Grandson of the Wise Man": "Donishmanding nabirasi",
    "The Demon Sword Master of Excalibur Academy": "Ilohiy qilich maktabining iblis qilich egasi",
    "Date A Live": "Jonli sana",
    "Date A Live Season 2": "Jonli sana 2-fasl",
    "Ride Your Wave": "Toʻlqiningni ushla",
    "Parasyte": "Kulrang parazit",
    "The Reincarnation of the Unlucky": "Omadsizning qayta tug'ilishi",
    "The Reincarnation of the Unlucky Season 2": "Omadsizning qayta tug'ilishi 2-fasl",
    "Love of Demons": "Iblislar sevgisi",
    "The Boy from the Village Near the Most Dangerous Dungeon": "Eng qiyin zindon oldida joylashgan qishloq bolasining hikoyasi",
    "Strange Contract with a Strange Demon": "G'alati iblis bilan g'alati shartnoma",
    "Fire Force": "Yorqin olov jodugarlari",
    "Sankarea": "Sankarea",
    "Seven Emotions of Merging": "Birlashishning yettita hissi",
    "Hentai": "Hentai",
    "The Story of the Old Couple Returning to Youth": "Yoshlikga qaytgan bobo va buvining hikoyasi",
    "Alien Sword": "Begona qilich",
    "Keijo": "Keijo",
    "That Girl is Lonely": "U qiz yolg'iz",
    "Temple of the Nuns": "Rohibalar ibodatxonasi",
    "Paradise Lies Under Mother's Feet": "Jannat onalar oyog'i ostida",
    "Perfect Lovers ❤️": "Mukkammal sevishganlar ❤️",
    "I Want to Eat Your Pancreas": "Seni oshqozon osti bezingni yemoqchiman",
    "Bridge to Terabithia": "Terabityaga sayohat 🥲",
    "Vinland Saga Season 1": "Vinland saga 1-fasl",
    "Vinland Saga Season 2": "Vinland saga 2-fasl",
    "Kaiju": "Kaiju",
    "Battle in the Live Broadcast": "Jonli efirdagi jang",
    "Ron Kamonohashi: Deranged Detective": "Kamonohashi Ron: Telba detektiv",
    "Working for a God in a Godless World": "Mabudsiz dunyoda mabud uchun ishlash",
    "The Angel Next Door": "Qo'shni farishta",
    "Yesterday's Crystal Sky": "Kechagi billur osmon",
    "Hello World": "Salom dunyo",
    "Our Story: Experienced You and Inexperienced Me": "Bizning hikoyamiz: Tajribali sen va tajribasiz men",
    "The Cat in Housekeeping is Still Silent": "Uy hizmatidagi mushuk yana homush",
    "The Dangers in My Heart": "Qalbimdagi Xavf-Xatar",
    "My Happy Marriage": "Mening Baxtli Nikohim",
    "Harem in the World": "Dunyodagi garem",
    "Violet Evergarden": "Violet Evergarden",
    "Ben 10": "Ben10",
    "DOTA: Dragon’s Blood": "DOTA: Ajdarning qoni",
    "DOTA: Dragon’s Blood Season 2": "DOTA: Ajdarning qoni 2-fasl",
    "Plastic Memories": "Plastik hotiralar",
    "Sniper Mask": "Snayper niqobi",
    "Love Shadow in the Hidden Room": "Yashirin xonadagi sevgi soyasi",
    "No Chance Against Instant Death in Another World!": "O'zga dunyo bir zumda o'lim kuchiga qarshi hech qanday imkoniyatga ega emas!",
    "Faraway Paladin": "Uzoq paladin",
    "SSSS.Gridman": "SSSS gridman",
    "Sky Battles": "Osmondagi janglar",
    "Sky Battles Season 2": "Osmondagi janglar 2-fasl",
    "Sky Battles Season 3": "Osmondagi janglar 3-fasl",
    "Sky Battles Season 4": "Osmondagi janglar 4-fasl",
    "Sky Battles OVA": "Osmondagi janglar (OVA) qismlar",
    "Assassination Classroom": "Qotillar sinfi",
    "Hero Classroom": "Qahramonlar sinfi",
    "Beast Tamer": "Yirtqich hayvonlar yo'li",
    "Low-Ranked Ninja": "Past malakali ninja",
    "White Cat Project": "Oq mushuk loyihasi",
    "Samurai Champloo": "Samurai Champloo",
    "I Did Everything to Live Comfortably": "Bekami ko'st yashashim uchun hamma narsa qildim",
    "Beelzebub": "Velzevul",
    "Chronicles of the Unrivaled Bahamut": "Yengilmas Bahamut yilnomalari",
    "The Laid-Back Black Soldier": "Ishdan bo'shatilgan qora askarning hayoti",
    "Kengan Ashura": "Kengan Ashura o'yini",
    "Reborn Groom in Another World": "O'zga dunyoda qayta tug'ilgan kuyov",
    "Reborn Groom in Another World Season 2": "O'zga dunyoda qayta tug'ilgan kuyov 2-fasl",
    "Dad Friends": "Do'st otalar",
    "Return of the Hero": "Qahramonning qaytishi",
    "Infinite Skateboard": "Cheksiz Skeybord",
    "How a Realist Hero Rebuilt the Kingdom": "Realizm qahramoni qirollikni qayta qurushi.",
    "Even Another World Can't Handle Instant Death": "Boshqa dunyo bir zum o'lim kuchiga dosh berolmaydi",
    "Spy x Family Season 2": "Josus x oilasi 2-fasl",
    "Giving Up on Heroism": "Qahramonlikdan voz kechib",
    "Bucchigiri": "Bucchigiri",
    "My Cousin is an Alien": "Mening amakivachcham o'zga sayyoralik",
    "Forced Pairing": "Majburiy juftlik",
    "Bottom-Tier Character Tomozaki": "Past darajali Tomozaki",
    "Forgive Me, Great Master": "Meni kechiring buyuk hojam",
    "Forgive Me, Great Master Season 2": "Meni kechiring buyuk hojam 2-fasl",
    "Mysterious Disappearances": "Sirli gʻoyib boʻlishlar",
    "Banished Hero": "Badargʻa qilingan qahramon",
    "The Yozakura Family": "Yozakura oilasi",
    "A Room with the Sun and an Angel": "Bir xonada quyosh va farishta",
    "My Hero Academia Season 7": "Mening qahramonlik akademiyam 7-fasl",
    "Panty Watchers": "Kalgotkalarni kuzatib",
    "One Punch Sister": "Bir zarbali opam",
    "Nisekoi": "Soxta sevgi",
    "Nisekoi Season 2": "Soxta sevgi 2-fasl",
    "Nisekoi OVA": "Soxta sevgi (OVA)",
    "The Ice Guy and His Cool Female Colleague": "Muz yigit va ajoyib qiz - hamkasblar",
    "Cupid Chocolates": "Cupidon shokoladlari",
    "Terrifying Aliens": "Daxshatli kelgindilar",
    "My Girlfriend": "Mening Qiz do'stim",
    "My Girlfriend Season 2": "Mening Qiz do'stim 2-fasl",
    "Deception Princess Himigato": "Aldash malikasi Himigato",
    "Made in Abyss": "Jarlikda Yaratilgan",
    "Nobunaga's Ambition": "Nobunaning ambitsiyasi",
    "Saving 80,000 Gold Coins to Start a New Life": "80.000 oltin tanga to'plab yangi hayotimni quraman",
    "The Devil is a Part-Timer": "Iblislar lordi va qahramon",
    "The Grandson of the Wise Man": "Donishmanding nabirasi",
    "The Demon Sword Master of Excalibur Academy": "Ilohiy qilich maktabining iblis qilich egasi",
    "Date A Live": "Jonli sana",
    "Date A Live Season 2": "Jonli sana 2-fasl",
    "Ride Your Wave": "Toʻlqiningni ushla",
    "Parasyte": "Kulrang parazit",
    "The Reincarnation of the Unlucky": "Omadsizning qayta tug'ilishi",
    "The Reincarnation of the Unlucky Season 2": "Omadsizning qayta tug'ilishi 2-fasl",
    "Love of Demons": "Iblislar sevgisi",
    "The Boy from the Village Near the Most Dangerous Dungeon": "Eng qiyin zindon oldida joylashgan qishloq bolasining hikoyasi",
    "Strange Contract with a Strange Demon": "G'alati iblis bilan g'alati shartnoma",
    "Fire Force": "Yorqin olov jodugarlari",
    "Sankarea": "Sankarea",
    "Seven Emotions of Merging": "Birlashishning yettita hissi",
    "Hentai": "Hentai",
    "The Story of the Old Couple Returning to Youth": "Yoshlikga qaytgan bobo va buvining hikoyasi",
    "Alien Sword": "Begona qilich",
    "Keijo": "Keijo",
    "That Girl is Lonely": "U qiz yolg'iz",
    "Temple of the Nuns": "Rohibalar ibodatxonasi",
    "Paradise Lies Under Mother's Feet": "Jannat onalar oyog'i ostida",
    "Perfect Lovers ❤️": "Mukkammal sevishganlar ❤️",
    "I Want to Eat Your Pancreas": "Seni oshqozon osti bezingni yemoqchiman",
    "Bridge to Terabithia": "Terabityaga sayohat 🥲",
    "Vinland Saga Season 1": "Vinland saga 1-fasl",
    "Vinland Saga Season 2": "Vinland saga 2-fasl",
    "Kaiju": "Kaiju",
    "Battle in the Live Broadcast": "Jonli efirdagi jang",
    "Ron Kamonohashi: Deranged Detective": "Kamonohashi Ron: Telba detektiv",
    "Working for a God in a Godless World": "Mabudsiz dunyoda mabud uchun ishlash",
    "The Angel Next Door": "Qo'shni farishta",
    "Yesterday's Crystal Sky": "Kechagi billur osmon",
    "Hello World": "Salom dunyo",
    "Our Story: Experienced You and Inexperienced Me": "Bizning hikoyamiz: Tajribali sen va tajribasiz men",
    "The Cat in Housekeeping is Still Silent": "Uy hizmatidagi mushuk yana homush",
    "The Dangers in My Heart": "Qalbimdagi Xavf-Xatar",
    "My Happy Marriage": "Mening Baxtli Nikohim",
    "Harem in the World": "Dunyodagi garem",
    "Violet Evergarden": "Violet Evergarden",
    "Ben 10": "Ben10",
    "DOTA: Dragon’s Blood": "DOTA: Ajdarning qoni",
    "DOTA: Dragon’s Blood Season 2": "DOTA: Ajdarning qoni 2-fasl",
    "Plastic Memories": "Plastik hotiralar",
    "Sniper Mask": "Snayper niqobi",
    "Love Shadow in the Hidden Room": "Yashirin xonadagi sevgi soyasi",
    "No Chance Against Instant Death in Another World!": "O'zga dunyo bir zumda o'lim kuchiga qarshi hech qanday imkoniyatga ega emas!",
    "Faraway Paladin": "Uzoq paladin",
    "SSSS.Gridman": "SSSS gridman",
    "Sky Battles": "Osmondagi janglar",
    "Sky Battles Season 2": "Osmondagi janglar 2-fasl",
    "Sky Battles Season 3": "Osmondagi janglar 3-fasl",
    "Sky Battles Season 4": "Osmondagi janglar 4-fasl",
    "Sky Battles OVA": "Osmondagi janglar (OVA) qismlar",
    "Assassination Classroom": "Qotillar sinfi",
    "Hero Classroom": "Qahramonlar sinfi",
    "Beast Tamer": "Yirtqich hayvonlar yo'li",
    "Low-Ranked Ninja": "Past malakali ninja",
    "White Cat Project": "Oq mushuk loyihasi",
    "Samurai Champloo": "Samurai Champloo",
    "I Did Everything to Live Comfortably": "Bekami ko'st yashashim uchun hamma narsa qildim",
    "Beelzebub": "Velzevul",
    "Chronicles of the Unrivaled Bahamut": "Yengilmas Bahamut yilnomalari",
    "The Laid-Back Black Soldier": "Ishdan bo'shatilgan qora askarning hayoti",
    "Kengan Ashura": "Kengan Ashura o'yini",
    "Reborn Groom in Another World": "O'zga dunyoda qayta tug'ilgan kuyov",
    "Reborn Groom in Another World Season 2": "O'zga dunyoda qayta tug'ilgan kuyov 2-fasl",
    "Dad Friends": "Do'st otalar",
    "Return of the Hero": "Qahramonning qaytishi",
    "Infinite Skateboard": "Cheksiz Skeybord",
    "How a Realist Hero Rebuilt the Kingdom": "Realizm qahramoni qirollikni qayta qurushi.",
    "Even Another World Can't Handle Instant Death": "Boshqa dunyo bir zum o'lim kuchiga dosh berolmaydi",
    "Spy x Family Season 2": "Josus x oilasi 2-fasl",
    "Giving Up on Heroism": "Qahramonlikdan voz kechib",
    "Bucchigiri": "Bucchigiri",
    "My Cousin is an Alien": "Mening amakivachcham o'zga sayyoralik",
    "Forced Pairing": "Majburiy juftlik",
    "Bottom-Tier Character Tomozaki": "Past darajali Tomozaki",
    "Forgive Me, Great Master": "Meni kechiring buyuk hojam",
    "Forgive Me, Great Master Season 2": "Meni kechiring buyuk hojam 2-fasl",
    "Mysterious Disappearances": "Sirli gʻoyib boʻlishlar",
    "Banished Hero": "Badargʻa qilingan qahramon",
    "The Yozakura Family": "Yozakura oilasi",
    "A Room with the Sun and an Angel": "Bir xonada quyosh va farishta",
    "My Hero Academia Season 7": "Mening qahramonlik akademiyam 7-fasl",
    "Panty Watchers": "Kalgotkalarni kuzatib",
    "One Punch Sister": "Bir zarbali opam",
    "Nisekoi": "Soxta sevgi",
    "Nisekoi Season 2": "Soxta sevgi 2-fasl",
    "Nisekoi OVA": "Soxta sevgi (OVA)",
    "The Ice Guy and His Cool Female Colleague": "Muz yigit va ajoyib qiz - hamkasblar",
    "Cupid Chocolates": "Cupidon shokoladlari",
    "Terrifying Aliens": "Daxshatli kelgindilar",
    "My Girlfriend": "Mening Qiz do'stim",
    "My Girlfriend Season 2": "Mening Qiz do'stim 2-fasl",
    "Deception Princess Himigato": "Aldash malikasi Himigato",
    "Made in Abyss": "Jarlikda Yaratilgan",
    "Nobunaga's Ambition": "Nobunaning ambitsiyasi",
    "Saving 80,000 Gold Coins to Start a New Life": "80.000 oltin tanga to'plab yangi hayotimni quraman",
    "The Devil is a Part-Timer": "Iblislar lordi va qahramon",
    "Code Geass": "Kod Giass",
    "Dance with Devils": "Iblislar bazmi",
    "Aura: The Last Battle of Koga Maryuin": "Aura: Koga Maryuinning soʻnggi jangi",
    "The Eternity of Eternity": "Abadiyatning abadiyligi",
    "Food Wars!": "Taomlar jangi",
    "Food Wars! (OVA)": "Taomlar jangi (OVA)",
    "Food Wars! Season 2": "Taomlar jangi 2-fasl",
    "Hellsing: The Dawn": "Hellsing: Jahannam urushi",
    "Black Butler": "O'lim gersogi va uning qora xizmatkori",
    "The Ancient Magus' Bride": "Sehrgarning kelini",
    "Talentless Nana": "Qobilyatsiz Nana",
    "Miss Kobayashi's Dragon Maid": "Miss Kobayashining ajdarho xizmatkorlari",
    "Even I Would Fall in Love with a Chuunibyou": "Men hatto chunibyoni ham sevib qolishni xoxlayman",
    "BOFURI: I Don't Want to Get Hurt, So I'll Max Out My Defense": "Shikastlanishni istamasdim, shuning uchun himoyamni kuchaytirdim",
    "BOFURI Season 2": "Shikastlanishni istamasdim, shuning uchun himoyamni kuchaytirdim 2-fasl",
    "Beyond the Sky": "Osmon ustida",
    "The One Who Loved You": "Seni sevgan yagona inson",
    "My Demon": "Mening iblisim",
    "Brothers’ Final Battle": "Og'a-inilar so'nggi jangi",
    "The Daily Life of the Immortal King": "O'lmas qirolning kundalik hayoti",
    "The Daily Life of the Immortal King Season 2": "O'lmas Qirolning kundalik hayoti 2-fasl",
    "The Daily Life of the Immortal King Season 3": "O'lmas Qirolning kundalik hayoti 3-fasl",
    "The Reincarnation of the Unlucky Guy Part 2": "Omadsizning qayta tug'ilishi 2-fasl 2-bo'lim",
    "The Daily Life of the Immortal King Season 4": "O'lmas Qirolning kundalik hayoti 4-fasl",
    "My Daughter is a Celestial Disaster": "Mani qizcham samoviy ofat",
    "Bubble": "Pufak",
    "Fire Force": "Alangali o't o'chiruvchilar brigadasi",
    "Mr. Villain’s Day Off": "Janob yovuzning dam olish kuni",
    "Four Knights": "To'rt ritsar",
    "Heavenly Grace": "Samoviy marhamat",
    "Gosick": "Gotika",
    "Moriarty the Patriot": "Patriot Moriarti",
    "Lookism": "Lookism",
    "The Tale of a Lying Hero": "Yolg'onchi qahramon hikoyasi",
    "Kaguya-sama: Love Is War Season 3": "Kaguya xonim: sevgi bu jang 3-fasl",
    "Kaguya-sama: Love Is War (OVA)": "Kaguya xonim: sevgi bu jang (OVA)",
    "My Sister the Demon Queen": "Singlim Ibilislar malikasi",
    "My Sister the Demon Queen (OVA)": "Singlim Ibilislar malikasi (OVA)",
    "Moriarty the Patriot Season 2": "Patriot Moriarti 2-fasl",
    "Spice and Wolf": "Bo'ri qiz va ziravorlar",
    "Akashic Records of Bastard Magic Instructor": "Akashic Records: Eng Yomon Sehr O'qituvchisi",
    "Monster Kid": "Maxluq bolasi",
    "My Girlfriend is a Demon": "Mening qiz do'stim jin",
    "The Gun Shop for Ladies and Gentlemen": "Xonimlar va janoblar uchun qurol do'koni",
    "Kizumonogatari": "Kizumonogatari",
    "Chainsaw Princess of the Demon City Defense Corps": "Iblis Shahrining Himoyachi Otryadining Quli Zanjirli Qul Malikasi",
    "Hunter x Hunter": "Ovchi x Ovchi",
    "Kengan Ashura Season 2": "Kengan Ashura o'yini 2-fasl",
    "How to Love My Elf Wife": "Elf rafiqamni qanday sevishim mumkin?",
    "Let Me Sing My Love Song": "Sevgi qo'shig'imni kuylashga ruxsat bering",
    "Angel of Death": "O'lim farishtasi",
    "Infinite Power Season 2": "Abadiy qudrat 2-fasl",
    "Infinite Power Season 3": "Abadiy qudrat 3-fasl",
    "Infinite Power Season 4": "Abadiy qudrat 4-fasl",
    "Infinite Power Season 5": "Abadiy qudrat 5-fasl",
    "Suicide Squad: Another World": "Oʻz joniga qasd qiluvchilar guruhi : o'zga dunyoda",
    "Lv2 Maxed-Cheat Skill in Another World": "Lv2 super aldash mahoratim bilan o'zga dunyoda hayot",
    "The Case Study of Vanitas": "Vanitasning xotiralari",
    "The New Gate": "Yangi darvoza",
    "A Condition Called Love": "Sevgi deb atalgan shart",
    "The Richest Player in the Game": "O'yindagi eng boy odam",
    "Alya Sometimes Flirts in Russian": "Alya ba'zan men bilan rus tilida noz-karashma qiladi",
    "Idol Children Season 2": "Idol farzandlari 2-fasl",
    "Is My Senpai a Boy?": "Mening senpayim o'g'il bolami?",
    "Failure Frame": "Muvaffaqiyatsizlik ramkasi: Men eng kuchli bo'ldim va past darajadagi afsunlar bilan hamma narsani yo'q qildim",
    "Young Samurai’s Escape Mastery": "Yosh samuray qochish ustasi",
    "I Want to Be the World's Best Adventurer": "Men dunyodagi eng yaxshi sarguzashtchi bo'lishni xoxlayman",
    "My Reindeer Friend Nokotan": "Mening bug'u do'stim Nokotan",
    "Why Did Everyone Forget My World?": "Nega hamma meni dunyoyimni unutdi?",
    "Unauthorized in Another World": "O'zga dunyoda ruxsatsiz",
    "Wistoria: Wand and Sword": "Wistoria: Tayoq va qilich",
    "After the Rain": "Yomg'irdan So'ng",
    "Osamake: A Romantic Comedy": "Osamake-kun Sevgi yo‘lida",
    "My Bodyguard": "Mening tansoqchim",
    "Tower of God Season 2": "Mabud minorasi 2-fasl",
    "NieR:Automata Ver1.1a Season 2": "NIER AVTOMATLAR 2-FASL",
    "The Duke's Contractual Fiancee": "Gertsokni shartnomali qallig'i",
    "I Became the Strongest With My Useless Skill": "Men muvaffaqiyatsiz mahoratim bilan eng kuchli bo'lib, hamma narsni yo'q qilaman",
    "Zetman": "Zet odam",
    "Star in the Darkness": "Zulmatdagi Yulduz",
    "So Many Girls Who Lost in Love": "Sevgida yutqizgan qizlar namuncha ko'p",
    "Black Clover": "Qora Klever",
    "Black Clover: Sword of the Wizard King": "Qora Klever: Afsungar qirolining qilichi",
    "Days With My Step-Sister": "O'gay singlim bilan o'tgan kunlar",
    "My Wife Has No Emotions": "Xotinimning his-tuygʻulari yoʻq",
    "The Cat Returns": "Mushukning qaytishi",
    "Bleach": "Bleach",
    "Golden Bugs Shine in the Forest": "O'rmonda tilla qo'ng'izlar yaltillaydi",
    "She Forgot Her Love Glasses": "Men sevga qiz ko'zoynaklarini unutdi",
    "Masamune-kun's Revenge Season 1": "Masamune-kunning sevgi intiqomi 1-fasl",
    "Anonymous Memory": "Nomsiz xotira",
    "The Return of the Silver King": "Kumush qirolning qayta tugʻilishi",
    "The Tale of the Moon Princess": "Oy malikasi haqidagi ertak",
    "Toilet-Bound Hanako-kun": "Hojatxonaga bog'langan Hanako",
    "Even I Might Fall for a Chuunibyou Season 2": "Men hatto chunibyoni sevib qolishim mumkin 2-fasl",
    "Spice and Wolf Season 2": "Bo'ri va ziravorlar 2-fasl",
    "The Magical Girl and the Evil Lieutenant Used to Be Enemies": "Sehrli qiz va yovuz letenant bir paytlar bosh dushman bo'lgan",
    "Renegade Immortal": "Renegade Immortal",
    "Terminator Zero": "Terminator Zero",
    "Insane Passion Season 2": "Aqildan Ozgan Ehtiros 2-fasl"
}


